set-option -sa terminal-overrides ",xterm*:Tc"
set -g mouse on

unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D 
bind k select-pane -U
bind l select-pane -R

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set -g history-limit 1000000
set -gq allow-passthrough on
set -g visual-activity off
# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

bind -n M-k switch-client -p
bind -n M-j switch-client -n
bind -n M-l next-window
bind -n M-h previous-window

bind -n M-v copy-mode

bind -n F10 run-shell '/home/ghost/dotfiles/.config/tmux/popuptmux.sh'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'jimeh/tmux-themepack'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'noscript/tmux-mighty-scroll'
set -g @plugin 'jabirali/tmux-normalmode'

 set -g @normalmode-prompt '❯'

set -g @continuum-restore 'on'
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-processes 'lazygit btop spf python3'
set -g @mighty-scroll-show-indicator 'on'

# set vi-mode
set-window-option -g mode-keys vi

set -g @themepack 'powerline/block/blue'

set -goq @themepack-status-right-area-left-format "%H:%M"
set -goq @themepack-status-right-area-middle-format "%b %d"

set -goq @themepack-status-right-area-right-format "#($HOME/dotfiles/.config/tmux/str.sh '#{pane_current_path}')"
set -goq @themepack-window-status-current-format "#I #W"
set -goq @themepack-window-status-format "#I #W"

set -g @sessionx-prefix off
set -g @sessionx-bind 'M-/'
set -g @sessionx-filter-current 'false'

set -g @sessionx-bind-select-up 'alt-k'
set -g @sessionx-bind-select-down 'alt-j'

set -g @sessionx-preview-location 'right'
set -g @sessionx-preview-ratio '65%'

set -g @sessionx-window-height '50%'
set -g @sessionx-window-width '60%'

set -goqF @powerline-status-left-area-left-fg "color255"

set -goq @theme-status-left '#[fg=#{@powerline-status-left-area-left-fg},bg=#{@powerline-status-left-area-left-bg},bold] #S '
set -goq  @theme-status-justify left

set -goqF @theme-window-status-current-fg "color255"
set -goqF @theme-window-status-current-bg "black"
set -goqF @theme-window-status-bg "colour233"

# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

bind 'c' new-window -c "#{pane_current_path}"

bind 'h' set status 
bind 'r' send reset Enter

# remove confirmations
bind 'x' kill-pane
bind '&' kill-window

unbind -T copy-mode-vi MouseDragEnd1Pane

set -g status-position top

set-option -g automatic-rename on

set -g mode-style bg="color235"
set -g status on
run '~/.config/tmux/plugins/tpm/tpm'
