[env] 
TERM = "xterm-256color"

[window]
startup_mode="Fullscreen"
# opacity=0.7
# decorations="None"

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen"},
{key = 'N', mods="Shift|Control", action="CreateNewWindow"},
]

[font]
size=13

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[colors.primary]
background = "0x09090f"
foreground = "0xD9E0EE"
# background = "0x191c1d"

[colors.cursor]
text = "0x1E1D2F"
cursor = "0xF5E0DC"

[colors.normal]
black = "0x232627"
red = "0xed1515"
green = "0x11d116"
yellow = "0xf67400"
blue = "0x1d99f3"
magenta = "0x9b59b6"
cyan = "0x1abc9c"
white = "0xfcfcfc"

[colors.bright]
black = "0x7f8c8d"
red = "0xc0392b"
green = "0x1cdc9a"
yellow = "0xfdbc4b"
blue = "0x3daee9"
magenta = "0x8e44ad"
cyan = "0x16a085"
white = "0xffffff"

[[colors.indexed_colors]]
index = 16
color = "0xF8BD96"

[[colors.indexed_colors]]
index = 17
color = "0xF5E0DC"
